import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"h-full"} data-new-gr-c-s-check-loaded="14.1233.0" data-gr-ext-installed="">
        <NavBar/>
            {children}
        <div></div>
      </body>
    </html>
  );
}
